[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Specify the Solidity compiler explicitly (path only)
solc = "/home/felix/solc/solc"

# Disable auto-detect
auto_detect_solc = false
offline = true

optimizer = true
optimizer_runs = 200
